In [ ]:
# numpy is short for numerical python
# it is written in C language, which means it's way more faster than a normal python list
# It is the foundational library for Data Science, Machine Learning, and Artificial Intelligence
# Almost all other data libraries (like Pandas) are built on top of NumPy

In [ ]:
# First of all, you have to download numpy library:

# do it by writing in the terminal : pip install numpy

In [1]:
# after that we need to import numpy in our file, we write : import numpy as np
# what (as np) part ?? it's just a nickname, instead of writing the word "numpy"
# we can call it anything, but for convenience part, we make it np

import numpy as mind_cloud

print(f"Numpy version is: {mind_cloud.__version__}")

# and it will work !! but it looks exhausting

Numpy version is: 2.3.5


In [2]:
# numpy allows doing arithmatic operations on numbers in lists, opposite to the regular list
# example : myltiplying by a constant
# =======================================

import numpy as np

x = [1,2,3]
y = np.array([1,2,3])

x = 2 * x
y = 2 * y
print(x)
print(y)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
# ================================= Dimension of the array =================================
import numpy as np

array_1 = np.array([1])
print(array_1.ndim)

array_2 = np.array([[1,2],
                    [3,4]])
print(array_2.ndim)

# please pay attention to the number of brackets and how does that relate to the number of dimensions

array_3 = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print(array_3.ndim)

# please pay attention to the fact that you can't have a numpy array that isn't homogeneous -
# in the arrays that have equal to or more than 2 dimensions
# example:
# array_4 = np.array([[1,2],
#                     [3]])
# print(array_4.ndim)



# ==================================================
# chain indexing: as we access the list items by list[0], since we have something called multidimensional array
# we also have multidimensional indexing
print("===============================================")
print(array_2[0,0]) # first raw, first column
print(array_3[0,0,0]) # first layer, first raw, first column

# In python, there's also chain indexing but it is written as this:
# list [0][0]
# this works in python, but the [0,0,0] way doesn't work in normal lists

In [ ]:
# ### Generating Arrays: Zeros and Ones
# Often, you need to create an array of a specific size, but you don't have the data for it yet. You just need a "blank placeholder." 

# NumPy gives us `np.zeros()` to fill an array with 0s, and `np.ones()` to fill an array with 1s.

# Where does it fit in our team's work ?? 
#  Why do we care about a matrix full of zeros? In **ROS2** (Robot Operating System), we use `np.zeros()` to create an *Occupancy Grid*. 

# Think of it like a blank map for a robot. The whole map starts as `0` (free space).
# As the robot's sensors detect obstacles (like walls or chairs), it changes those specific `0`s into `1`s (occupied space).
# `np.zeros()` gives the robot its blank canvas to start mapping the room!

In [ ]:
import numpy as np

# Note: the shape (5, 5) needs to be inside its own set of parentheses!
blank_map = np.zeros((5, 5))

print(blank_map)

# The values are updated by a sensor later, like a lidar
# blank_map[2, 2] = 1  # Robot found an obstacle in the middle!

In [3]:
# ====================== Array Slicing ======================
# Slicing means that we will take a (slice) from the already existing array
import numpy as np
array_4 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
# we may write "array[start:stop]", and we can also use "array[start:stop:step]"

print(array_4[0:2]) # remember that, like the command "(for i in range(3))" that the last number is excluded
print("===============================================")
print(array_4[0:4:2]) # it means that we want the sliced array from index 0 to index 3 (remember, the last number is excluded) so 
# we may also make the same array with the next order
print(array_4[::2]) # since the start:stop are default with the starting and ending of the whole array
# if we want the very start and the very ending we don't have to write them explicitly
print("===============================================")
# we can also reverse the order of the array by the same command
print(array_4[::-1]) # making the step by -1 so the movements are reversed

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
# The prevoius cell was to deal with the rows of the array, we can also deal with the columns of the array
# remember, we're dealing with a 2-d array, so it looks like this array_4[rows,columns]
import numpy as np
array_4 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
print(array_4[:,2]) # we use ":" in the place of the rows, so we select all of the rows, if we want a specific part, we can use the prevoius examples
# for example, that line will print the column number 3
print("===============================================")
print(array_4[:,0:3]) # that will print the first 3 columns, from index 0 to index 2
print("===============================================")
# now, we can manipulate freely any 2-d array by selecting a specific section of the array
print(array_4[:2,:2])

In [ ]:
# ====================== scalar arithmetic functions ======================
import numpy as np
array_5 = np.array([1,2,3,4])
print(array_5 + 1)
print(array_5 - 2)
print(array_5 * 5)
print(array_5 / 2)
print(array_5 ** 3)

In [ ]:
# ====================== vectorized arithmetic functions ======================
import numpy as np
array_6 = np.array([1,2,3.5])
# Please notice that after printing the output, all the numbers must have the point "." as if it's float 
print(np.sqrt(array_6))
print(np.round(array_6))
print(np.floor(array_6))
print(np.ceil(array_6))

In [ ]:
# We can merge the scaler operations and vectorized operations
import numpy as np
radii = np.array([1,2,3])
# for example, that array is the radii (plural for radius) and we want to get the area for all of them, by the formula A = πr²
area = np.pi * radii ** 2
print(area)

In [ ]:
# Comparison operator "IMPORTANT"
import numpy as np
scores = np.array([33,70,92,100,59,80,88])

print( scores >= 60 )

scores [scores<=80] = 0

print(scores) # this can act as a filteration for the values of the array

In [ ]:
# ====================== Array shape ======================
import numpy as np

array_3 = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print(array_3.shape)
# (2,2,2) : first 2 is how many layers in the array
# the second 2 is how many rows in each layer
# the third 2 is how many columns in each row

3


In [ ]:
# ====================== Broadcasting ======================
# What happens if you try to do math between two arrays that are **different sizes**?
# Normally, this would cause an error. 

# However, NumPy has a feature called **Broadcasting**.
# If the shapes are compatible, NumPy will automatically "stretch" the smaller array;
# to match the larger one so the math works.

# There are two rules in broadcasting, the two arrays are compatible when matching each dimention
# in cases:
# 1- the dimensions have the same size
# 2- one of the dimensions have the size of 1, it wil be easier to show in example 😅

In [ ]:
import numpy as np

array_7 = np.array([[1,2,3,4]]) # that's a 2-d array, with one row and 4 columns
array_8 = np.array([[1],
                    [2],
                    [3],
                    [4]]) # that's a 2-d array, with 4 rows and one column
# now let's print the shape of each array to see the dimensions I was talking about
print(array_7.shape)
print(array_8.shape)
# the output is now (1,4) and (4,1), now let's use them to specify whether broadcasting is available or not
# while matching the dimensions, let's take the rows in example, they are 1 and 4 in each
# are they equal? no, but is one of them is equal to 1 ? yes !!
# it means that the rows are compatible and broadcasting is doable in terms of rows
# now let's do the same with the number of columns in each array, we will see that they are 4 and 1
# are they equal? no, but is one of them is equal to 1 ? yes !!
# it means that the rows are compatible and broadcasting is doable in terms of columns
# so broadcasting is possible for both arrays !!

In [ ]:
# now let's start the practical example for broadcasting
import numpy as np

array_7 = np.array([[1,2,3,4]])
array_8 = np.array([[1],
                    [2],
                    [3],
                    [4]])
                    
print(array_7 * array_8)
# as you can see, it's 4 columns and 4 rows, which means broadcasting is done perfectly

In [ ]:
import numpy as np

array_7 = np.array([[1,2,3,4],
                    [5,6,7,8]])
array_8 = np.array([[1],
                    [2],
                    [3],
                    [4]])
print(array_7 * array_8)
# as you can see, the size now of both doesn't satisfy the conditions of broadcasting, so they aren't multiplied

In [ ]:
# ====================== Aggregate functions ======================
# they summarize data from the array and return a single value
array_9 = np.array([[1,2,3,4,5],
                    [6,7,8,9,10]])
print(np.sum(array_9)) # the sum of all elements in the array
print(np.mean(array_9)) # average of the array
print(np.min(array_9)) # minimum value of the array
print(np.max(array_9)) # max value of the array

In [ ]:
# ====================== Filtering ======================
# The process of selecting specific data from the array that matches certain conditions
# Let's say we have an array for scores of some students
students = np.array([[32,61,90,82,75,100,77,95,12,68],
                    [79,55,27,28,64,44,85,73,52,99]]) # notice that this is a 2-d array 👀
succedded = students [students >=50]
failed = students [students < 50]
# as you can see, we wrote the new array's variable first, then we added a condition on the original array
print(succedded)
print(failed)
# please notice that those both came as 1-d arrays, but what if I want to preserve the original size 🤔

In [ ]:
# there's a function that does something like that, called np.where()
import numpy as np
students = np.array([[32,61,90,82,75,100,77,95,12,68],
                    [79,55,27,28,64,44,85,73,52,99]]) 
succedded = np.where(students >= 50,students, 0)
# as you can see, there are 3 arguments, the first one "students >= 50" is the condition
# the "students" is the name of the array we are working on
# the "0" is the value I'm going to replace the other values that didn't suit the condition in the array with
print(succedded)
# the values that didn't satisfy the condition are all sets to zero
# please notice that the output is a 2-d array

In [ ]:
# ====================== Matrix operations ======================
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
print("="*15+" A "+"="*15)
print(A)
print("="*15+" B "+"="*15)
print(B)
print("="*15+" A + B "+"="*15)
print(A + B) # this is the addition of two arrays
print("="*15+" A - B "+"="*15)
print(A - B) # this is the subtraction of two arrays
print("="*15+" A * B "+"="*15)
print(A * B) # this is the multiplication of two arrays
print("="*15+" A @ B "+"="*15)
print(A @ B) # this is the matrix multiplication of two arrays
print("="*15+" A.dot(B) "+"="*15)
print(A.dot(B)) # this is the matrix multiplication of two arrays, but in a different way
print("="*15+" A.T "+"="*15)
print(A.T) # this is the transpose of the array A


=============== A ===============
[[1 2 3]
 [4 5 6]
 [7 8 9]]
=============== B ===============
[[9 8 7]
 [6 5 4]
 [3 2 1]]
=============== A + B ===============
[[10 10 10]
 [10 10 10]
 [10 10 10]]
=============== A - B ===============
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
=============== A * B ===============
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
=============== A @ B ===============
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
=============== A.dot(B) ===============
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
=============== A.T ===============
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# inversing a matrix is a bit more complicated than the other operations, but we can do it by using the function np.linalg.inv()
#determine if the matrix is invertible or not by calculating the determinant of the matrix, if it's equal to 0, then it's not invertible
C = np.array([[1,2],[3,4]])
C_inv = np.linalg.inv(C)
det_C = np.linalg.det(C)
if det_C == 0:
  print("The matrix is not invertible")
else:
  print("The matrix is invertible")
print("="*15+" C "+"="*15)
print(C)
print("="*15+" C_inv "+"="*15)
print(C_inv)

The matrix is invertible
=============== C ===============
[[1 2]
 [3 4]]
=============== C_inv ===============
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# we can reshape the array by using the function np.reshape()
D = np.array([[1,2,3,4],[5,6,7,8]])
reshaped_D = np.reshape(D, (4,2)) # array , size
print("="*15+" D "+"="*15)
print(D)
print("="*15+" reshaped_D "+"="*15)
print(reshaped_D)

=============== D ===============
[[1 2 3 4]
 [5 6 7 8]]
=============== reshaped_D ===============
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# we can flatten the array by using the function np.flatten() and other functions like np.ravel() and np.reshape(-1)
flattened_D = D.flatten()
print("="*15+" flattened_D "+"="*15)
print(flattened_D)
flattened_D_ravel = np.ravel(D)
print("="*15+" flattened_D_ravel "+"="*15)
print(flattened_D_ravel)
flattened_D_reshape = np.reshape(D, -1)
print("="*15+" flattened_D_reshape "+"="*15)
print(flattened_D_reshape)


=============== flattened_D ===============
[1 2 3 4 5 6 7 8]
=============== flattened_D_ravel ===============
[1 2 3 4 5 6 7 8]
=============== flattened_D_reshape ===============
[1 2 3 4 5 6 7 8]


In [ ]:
# ====================== Random numbers ======================
# we can use the numpy library to generate a random number arrays (please pay attention to that fact, random arrays !!)
# we can use numpy to only get a radom number between two ranges
import numpy as np
rng = np.random.default_rng()
# rng = random number generator, it's like making a dice rolling machine 🎲 !!
# It's OOP by the way ....
print(rng.integers(1,100)) # this prints out a random value between 1 and 6 (the last number is excluded)
print(rng.integers(1,100, size = 3)) # I can make an array of size 3, it means a 1-d array with 3 elements
print(rng.integers(1,100, size = (3,3))) # now let's make a 2-d array with 3 columns and 3 rows

In [ ]:
# random seeding is a way to initialize the random number generator with a specific starting point, called a seed.
# This is useful when you want to reproduce the same sequence of random numbers for testing or debugging
rng = np.random.default_rng(seed=42)

In [ ]:
# we can shuffle the array by using the function np.random.shuffle()
import numpy as np
rng = np.random.default_rng() 

array_10 = np.array([1,2,3,4,5,6])
rng.shuffle(array_10)
print(array_10)